# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "3ximus/debian-xfce"
  config.vm.define "debian-custom"

  config.vm.provider 'libvirt' do |libvirt|
    # your libvirt settings
  end

  config.vm.synced_folder "./", "/vagrant", type: "virtiofs"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
end
